# Generated by Django 6.1 on 2026-09-23 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_firm_lsk_number'),
        ('matters', '0002_alter_matter_opened_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('event_type', models.CharField(choices=[('hearing', 'Hearing'), ('deadline', 'Deadline'), ('deposition', 'Deposition'), ('mediation', 'Mediation'), ('mention', 'Mention'), ('other', 'Other')], default='hearing', max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('court', models.CharField(blank=True, max_length=200)),
                ('judge', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('jicms', 'JICMS Sync')], default='manual', max_length=10)),
                ('jicms_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('adjourned', 'Adjourned'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='court_events', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.firm')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matters.matter')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
