# Generated by Django 6.1 on 2026-09-22 07:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matter',
            name='opened_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
