# Generated by Django 6.1 on 2026-09-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0002_alter_matter_opened_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matter',
            name='reference',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
